name: Pre-release
on:
  push:
    branches:
      - beta
      - "exp-*"

jobs:
  pre-release:
    name: pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org" # This registry URL is necessary for publishing on NPM
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Build Package
        run: npm run build
      - name: Pre-Release Package
        env:
          HUSKY: 0 # skip the husky hooks
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # should be set in Github repo, need this to publish on NPM
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by Github Actions, need this to create a GitHub Release
        run: |
          npx semantic-release
